[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clouds-ml"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
include = ["clouds*"]
